Added CMake

diff --git a/cpp-run b/cpp-run
--- a/cpp-run
+++ b/cpp-run
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 APP_NAME=cpp-run
-SRC_PATH=/usr/local/src/$APP_NAME/src
+src_dir=/usr/local/src/$APP_NAME/src
 BIN_PATH=/usr/local/src/$APP_NAME/bin
 OUTPUT_PATH=~/cpp-workspace
 
@@ -27,28 +27,41 @@ if [[ "$1" == "build" ]];
 				errorAndQuit
 		fi
 
-		PROJECT_NAME=$2
+		project_name=$2
 
 		if [[ "$3" == "." ]];
 			then
-				NAMESPACE=$2
+				namespace=$2
 			else
-				NAMESPACE=$3
+				namespace=$3
+		fi
+
+		if [[ -z "$4" ]];
+			then
+				build_type="debug"
+			else
+				build_type=$4
 		fi
 
 		current_time=$(timestamp)
 
-		SRC_PATH=$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE
-		output_bin=$OUTPUT_PATH/$PROJECT_NAME/bin
-		build_dir=$OUTPUT_PATH/$PROJECT_NAME/build/$NAMESPACE
-		include_dir=$OUTPUT_PATH/$PROJECT_NAME/include
+		src_dir=$OUTPUT_PATH/$project_name/src
+		output_bin=$OUTPUT_PATH/$project_name/bin
+		build_dir=$OUTPUT_PATH/$project_name/build/$namespace/$build_type
+		include_dir=$OUTPUT_PATH/$project_name/include
+		lib_dir=$OUTPUT_PATH/$project_name/lib
 
 		mkdir -p $output_bin/old/
 		mv $output_bin/*.* $output_bin/old/ 2> /dev/null
 
-		if [[ -z "$4" ]];
+		rm $build_dir/temp* 2> /dev/null
+
+		touch $build_dir/temp
+		touch $build_dir/temp2
+
+		if [[ -z "$5" ]];
 			then
-				cd $OUTPUT_PATH/$PROJECT_NAME
+				cd $OUTPUT_PATH/$project_name
 				git add .
 				git commit -a
 		fi
@@ -56,50 +69,77 @@ if [[ "$1" == "build" ]];
 		no_errors="yes"
 		built_file="no"
 
-		for f in $SRC_PATH/include/*.h;
+		# cmake -G "Unix Makefiles"
+
+		printf "cmake_minimum_required(VERSION 2.8)\n\n" > $build_dir/CMakeLists.txt
+		printf "project(\"$namespace\")\n\n" >> $build_dir/CMakeLists.txt
+
+		printf "include_directories(\"$src_dir\")\n" >> $build_dir/CMakeLists.txt
+
+		for f in $src_dir/*;
 		do
-			file=${f##*/}
-			file_name=${file::-4}
-			echo $include_dir/$NAMESPACE/$file
-			if ! [[ -e "$include_dir/$NAMESPACE/$file" ]] || [[ "$f" -nt "$include_dir/$NAMESPACE/$file" ]];
+			printf "include_directories(\"$f\")\n" >> $build_dir/CMakeLists.txt
+		done
+
+		printf "include_directories(\"$include_dir\")\n\n" >> $build_dir/CMakeLists.txt
+
+		printf "add_executable(\"$namespace\"\n" >> $build_dir/CMakeLists.txt
+
+		for f in $(find $src_dir/$namespace/src -name *.cpp);
+		do
+			printf "\t\"$f\"\n" >> $build_dir/CMakeLists.txt
+		done
+
+		printf ")\n\n" >> $build_dir/CMakeLists.txt
+
+
+		for f in $(find $src_dir/ \( -name "*.cpp" -o -name "*.h" \));
+		do
+			result="$(cat $f | grep "#include \"" | grep -v "#include \"include/")"
+			if ! [[ $result == "" ]];
 				then
-					cp $f $include_dir/$NAMESPACE/$file
+					echo "${result/\" #/\n}" >> $build_dir/temp
 			fi
 		done
 
-		for f in $SRC_PATH/src/*.cpp;
+	 	cat $build_dir/temp | sort -u | while read line;
 		do
-			file=${f##*/}
-			file_name=${file::-4}
-			if ! [[ -e "$build_dir/$file_name.o" ]] || [[ "$f" -nt "$build_dir/$file_name.o" ]];
-				then
-					python "$BIN_PATH/update_files.py" "build_inc" $f
-					if g++ -c $f -I $include_dir -o $build_dir/$file_name.out;
-						then
-							echo "Successfully built the $file." #> /dev/null
-							built_file="yes"
-						else
-							no_errors="no"
-					fi
-			fi
+			name=${line:10}
+			name=${name::-3}
+
+			printf "add_library(\".${name/"/"/"."}\" STATIC \"$lib_dir/$name.cpp\")\n" >> $build_dir/CMakeLists.txt
+			printf "target_link_libraries(\"$namespace\" \".${name/"/"/"."}\")\n\n" >> $build_dir/CMakeLists.txt
+
+			echo "\".${name/"/"/"."}\" " >> $build_dir/temp2
 		done
 
-		if [[ "$no_errors" == "yes" ]];
-			then
-				g++ $build_dir/*.out -o $output_bin/$current_time-$NAMESPACE.out
-				clear
-				$OUTPUT_PATH/$PROJECT_NAME/bin/$current_time-$NAMESPACE.out # > $output_bin/$NAMESPACE-$current_time.output
-			else
-				echo "Build failed."
-		fi
+		printf "set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY $lib_dir/compiled)\n" >> $build_dir/CMakeLists.txt
+		printf "set(CMAKE_LIBRARY_OUTPUT_DIRECTORY $lib_dir/compiled)\n" >> $build_dir/CMakeLists.txt
+		printf "set(CMAKE_RUNTIME_OUTPUT_DIRECTORY $output_bin)\n" >> $build_dir/CMakeLists.txt
 
-		if [[ "$built_file" == "yes" ]];
-			then
-				# Generate documentation
-				echo "" > /dev/null
-		fi;
-		# clear
-		# cat $output_bin/*.output
+		printf "\nset_target_properties(\"$namespace\"\n" >> $build_dir/CMakeLists.txt
+
+		for f in $(cat $build_dir/temp2)
+		do
+			printf "\t$f\n" >> $build_dir/CMakeLists.txt
+		done
+
+		printf "\tPROPERTIES\n" >> $build_dir/CMakeLists.txt
+		printf "\tARCHIVE_OUTPUT_DIRECTORY \"$lib_dir/compiled\"\n" >> $build_dir/CMakeLists.txt
+    	printf "\tLIBRARY_OUTPUT_DIRECTORY \"$lib_dir/compiled\"\n" >> $build_dir/CMakeLists.txt
+    	printf "\tRUNTIME_OUTPUT_DIRECTORY \"$output_bin\"\n" >> $build_dir/CMakeLists.txt
+		printf ")\n" >> $build_dir/CMakeLists.txt
+
+		rm $build_dir/temp* 2> /dev/null
+
+		cd $build_dir
+		cmake -G "Unix Makefiles" > /dev/null
+		make > /dev/null
+
+		cd $OUTPUT_PATH/$project_name/
+		git commit -a
+		clear
+		$output_bin/$project_name
 fi
 
 if [[ "$1" == "create" ]];
@@ -112,28 +152,32 @@ if [[ "$1" == "create" ]];
 
 		if [[ "$2" == "project" ]];
 			then
-				PROJECT_NAME=$3
+				project_name=$3
 
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/bin"
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/build/$PROJECT_NAME/"
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/doc"
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/include"
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/include/$PROJECT_NAME"
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/lib"
+				mkdir -p "$OUTPUT_PATH/$project_name/bin"
+				mkdir -p "$OUTPUT_PATH/$project_name/build/$project_name/Release"
+				mkdir -p "$OUTPUT_PATH/$project_name/build/$project_name/Debug"
+				mkdir -p "$OUTPUT_PATH/$project_name/doc"
+				mkdir -p "$OUTPUT_PATH/$project_name/include"
+				mkdir -p "$OUTPUT_PATH/$project_name/include/$project_name"
+				mkdir -p "$OUTPUT_PATH/$project_name/lib"
+				mkdir -p "$OUTPUT_PATH/$project_name/lib/compiled"
 				# Include, sample, scr
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/src/"
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/src/$PROJECT_NAME/include"
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/src/$PROJECT_NAME/src"
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/src/$PROJECT_NAME/doc"
+				mkdir -p "$OUTPUT_PATH/$project_name/src/"
+				mkdir -p "$OUTPUT_PATH/$project_name/src/$project_name/include"
+				mkdir -p "$OUTPUT_PATH/$project_name/src/$project_name/src"
+				mkdir -p "$OUTPUT_PATH/$project_name/src/$project_name/doc"
 
-				cp "$SRC_PATH/default_main.cpp" "$OUTPUT_PATH/$PROJECT_NAME/src/$PROJECT_NAME/src/Main.cpp"
+				cp "$src_dir/default_main.cpp" "$OUTPUT_PATH/$project_name/src/$project_name/src/Main.cpp"
 
-				python "$BIN_PATH/parse_new_files.py" "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE" "$@"
+				python "$BIN_PATH/parse_new_files.py" "$OUTPUT_PATH/$project_name/src/$namespace" "$@"
 
-				cd $OUTPUT_PATH/$PROJECT_NAME/
+				cd $OUTPUT_PATH/$project_name/
 				git init > /dev/null
+				# Make a .gitignore default mate.
 				echo 'bin/' > .gitignore
 				echo 'build/' >> .gitignore
+				echo 'lib/compiled' >> .gitignore
 				git add .
 				git commit -m "Initial project setup." > /dev/null
 		fi;
@@ -145,20 +189,20 @@ if [[ "$1" == "create" ]];
 						errorAndQuit
 				fi
 
-				PROJECT_NAME=$3
-				NAMESPACE=$4
+				project_name=$3
+				namespace=$4
 				CLASS_NAME=$5
 
-				cp "$SRC_PATH/default_class.cpp" "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/src/$CLASS_NAME.cpp"
-				cp "$SRC_PATH/default_header.h" "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/include/$CLASS_NAME.h"
+				cp "$src_dir/default_class.cpp" "$OUTPUT_PATH/$project_name/src/$namespace/src/$CLASS_NAME.cpp"
+				cp "$src_dir/default_header.h" "$OUTPUT_PATH/$project_name/src/$namespace/include/$CLASS_NAME.h"
 
-				python "$BIN_PATH/parse_new_files.py" "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/" "$@"
-				python "$BIN_PATH/update_files.py" "add_class" "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/src/Main.cpp" "$CLASS_NAME" "$NAMESPACE"
+				python "$BIN_PATH/parse_new_files.py" "$OUTPUT_PATH/$project_name/src/$namespace/" "$@"
+				python "$BIN_PATH/update_files.py" "add_class" "$OUTPUT_PATH/$project_name/src/$namespace/src/Main.cpp" "$CLASS_NAME" "$namespace"
 
-				cd $OUTPUT_PATH/$PROJECT_NAME/
-				git add src/$NAMESPACE/src/$CLASS_NAME.cpp
-				git add src/$NAMESPACE/include/$CLASS_NAME.h
-				git commit -m "Added '$CLASS_NAME' cpp and h to '$NAMESPACE' namespace." > /dev/null
+				cd $OUTPUT_PATH/$project_name/
+				git add src/$namespace/src/$CLASS_NAME.cpp
+				git add src/$namespace/include/$CLASS_NAME.h
+				git commit -m "Added '$CLASS_NAME' cpp and h to '$namespace' namespace." > /dev/null
 		fi;
 
 		if [[ "$2" == "namespace" ]];
@@ -168,17 +212,18 @@ if [[ "$1" == "create" ]];
 						errorAndQuit
 				fi
 
-				PROJECT_NAME=$3
-				NAMESPACE=$4
+				project_name=$3
+				namespace=$4
 
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/build/$NAMESPACE/"
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/include"
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/src"
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/doc"
-				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/include/$NAMESPACE"
+				mkdir -p "$OUTPUT_PATH/$project_name/build/$namespace/Release"
+				mkdir -p "$OUTPUT_PATH/$project_name/build/$namespace/Debug"
+				mkdir -p "$OUTPUT_PATH/$project_name/src/$namespace/include"
+				mkdir -p "$OUTPUT_PATH/$project_name/src/$namespace/src"
+				mkdir -p "$OUTPUT_PATH/$project_name/src/$namespace/doc"
+				mkdir -p "$OUTPUT_PATH/$project_name/include/$namespace"
 
-				cp "$SRC_PATH/default_main.cpp" "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/src/Main.cpp"
+				cp "$src_dir/default_main.cpp" "$OUTPUT_PATH/$project_name/src/$namespace/src/Main.cpp"
 
-				python "$BIN_PATH/parse_new_files.py" "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE" "$@"
+				python "$BIN_PATH/parse_new_files.py" "$OUTPUT_PATH/$project_name/src/$namespace" "$@"
 		fi;
 fi;
